### ISSUE TITLE
Bug tambah barang

### ISSUE THREAD

**Issue by plirapli** [FarelG/Proyek-semester1#9]
Ketika ditanya "Tambah Barang (Y/N)?" saya memilih n, namun barang tersebut tetap masuk ke keranjang.

**Comment by tsaniamagistra** [comment]
"Tambah Barang (Y/N)?"
Jika user memilih y berarti masih ada barang lain yang ingin ditambahkan dalam transaksi.
Jika user memilih n berarti sudah tidak ada barang lain yang ingin ditambahkan dan transaksi akan ditotal.
Mungkin kalimat "Tambah Barang (Y/N)?" harus diganti kalimat lain yang tidak rancu.
Terima kasih sarannya

**Comment by tsaniamagistra** [comment]
"Tambah Barang (Y/N)?"
Jika user memilih y berarti masih ada barang lain yang ingin ditambahkan dalam transaksi.
Jika user memilih n berarti sudah tidak ada barang lain yang ingin ditambahkan dan transaksi akan ditotal.
Mungkin kalimat "Tambah Barang (Y/N)?" harus diganti kalimat lain yang tidak rancu.
Terima kasih sarannya @plirapli

**Comment by FarelG** [comment]
Terima kasih sepuh🙏

**Comment by plirapli** [comment]
jir
